package tiktok

import (
	"crypto/rand"
	"encoding/binary"
	"time"
)

var apiHosts = []string{
	"api-boot.tiktokv.com",
	"api-h2.tiktokv.com",
	"api-m.tiktok.com",
	"api-normal.tiktokv.com",
	"api-ru.tiktokv.com",
	"api-t1.tiktokv.com",
	"api-t2.tiktokv.com",
	"api-va.tiktokv.com",
	"api.tiktokv.com",
	"api.us.tiktokv.com",
	"api15-h2.tiktokv.com",
	"api15-normal-alisg.tiktokv.com",
	"api15-normal-probe-alisg.tiktokv.com",
	"api15-normal-probe-useast1a.tiktokv.com",
	"api15-normal-probe-useast2a.tiktokv.com",
	"api15-va.tiktokv.com",
	"api16-normal-alisg.tiktokv.com",
	"api16-normal-apix-alisg.tiktokv.com",
	"api16-normal-apix-quic-alisg.tiktokv.com",
	"api16-normal-apix-quic-useast1a.tiktokv.com",
	"api16-normal-apix-quic-useast2a.tiktokv.com",
	"api16-normal-apix-quic.tiktokv.com",
	"api16-normal-apix-useast1a.tiktokv.com",
	"api16-normal-apix-useast2a.tiktokv.com",
	"api16-normal-baseline-alisg.tiktokv.com",
	"api16-normal-baseline-useast1a.tiktokv.com",
	"api16-normal-baseline-useast2a.tiktokv.com",
	"api16-normal-baseline.tiktokv.com",
	"api16-normal-c-alisg-ab.tiktokv.com",
	"api16-normal-c-alisg.tiktokv.com",
	"api16-normal-c-useast1a.tiktokv.com",
	"api16-normal-c-useast2a.tiktokv.com",
	"api16-normal-c.tiktokv.com",
	"api16-normal-c4-alisg.tiktokv.com",
	"api16-normal-c6-alisg.tiktokv.com",
	"api16-normal-delay-alisg.tiktokv.com",
	"api16-normal-i-alisg.tiktokv.com",
	"api16-normal-i.tiktokv.com",
	"api16-normal-n-alisg.tiktokv.com",
	"api16-normal-n.tiktokv.com",
	"api16-normal-no1a.tiktokv.eu",
	"api16-normal-probe-alisg.tiktokv.com",
	"api16-normal-probe-useast1a.tiktokv.com",
	"api16-normal-probe-useast2a.tiktokv.com",
	"api16-normal-quic-alisg.tiktokv.com",
	"api16-normal-quic-useast1a.tiktokv.com",
	"api16-normal-quic-useast2a.tiktokv.com",
	"api16-normal-useast1a.tiktokv.com",
	"api16-normal-useast2a.tiktokv.com",
	"api16-normal-useast5.tiktokv.us",
	"api16-normal-useast5.us.tiktokv.com",
	"api16-normal-v4.tiktokv.com",
	"api16-normal-v6.tiktokv.com",
	"api16-normal-ycru.tiktokv.com",
	"api16-normal.tiktokv.com",
	"api16-va.tiktokv.com",
	"api16.tiktokv.com",
	"api17-normal-probe-alisg.tiktokv.com",
	"api17-normal-probe-useast2a.tiktokv.com",
	"api19-normal-alisg.tiktokv.com",
	"api19-normal-c-alisg.tiktokv.com",
	"api19-normal-c-useast1a.tiktokv.com",
	"api19-normal-c-useast2a.tiktokv.com",
	"api19-normal-c4-alisg.tiktokv.com",
	"api19-normal-probe-alisg.tiktokv.com",
	"api19-normal-probe-useast1a.tiktokv.com",
	"api19-normal-probe-useast2a.tiktokv.com",
	"api19-normal-useast1a.tiktokv.com",
	"api19-normal-useast2a.tiktokv.com",
	"api19-normal.tiktokv.com",
	"api19-va.tiktokv.com",
	"api19.tiktokv.com",
	"api21-h2.tiktokv.com",
	"api21-normal-c-alisg.tiktokv.com",
	"api21-normal-c-useast2a.tiktokv.com",
	"api21-normal-c4-alisg.tiktokv.com",
	"api21-normal-c6-alisg.tiktokv.com",
	"api21-normal-i-alisg.tiktokv.com",
	"api21-normal-n-alisg.tiktokv.com",
	"api21-normal-probe-alisg.tiktokv.com",
	"api21-quic.tiktokv.com",
	"api21.tiktokv.com",
	"api22-normal-c-alisg.tiktokv.com",
	"api22-normal-c-useast1a.tiktokv.com",
	"api22-normal-c-useast2a.tiktokv.com",
	"api22-normal-c.tiktokv.com",
	"api22-normal-delay-alisg.tiktokv.com",
	"api22-normal-h-alisg.tiktokv.com",
	"api22-normal-n-alisg.tiktokv.com",
	"api22-normal-probe-alisg.tiktokv.com",
	"api22-normal-probe-quic-alisg.tiktokv.com",
	"api22-normal-probe-quic-useast1a.tiktokv.com",
	"api22-normal-probe-useast1a.tiktokv.com",
	"api22-normal-probe-useast2a.tiktokv.com",
	"api22-normal-v4.tiktokv.com",
	"api22-normal.tiktokv.com",
	"api22-quic.tiktokv.com",
	"api3-normal-useast1a.tiktokv.com",
	"api3-normal-useast2a.tiktokv.com",
	"api31-normal-probe-useast1a.tiktokv.com",
	"api31-normal-probe-useast2a.tiktokv.com",
	"api31-normal-useast1a.tiktokv.com",
	"api31-normal-useast2a.tiktokv.com",
	"api32-normal-no1a.tiktokv.eu",
	"api32-normal-useast2a.tiktokv.com",
	"api53-normal-c-useast1a.tiktokv.com",
	"api58-normal-c-useast1a.tiktokv.com",
	"api58-normal-useast2a.tiktokv.com",
	"api77-normal-c-useast1a.tiktokv.com",
	"api9-normal-useast2a.tiktokv.com",
}

func GetRandomAPIHost() string {
	if len(apiHosts) == 0 {
		return ""
	}
	b := make([]byte, 8)
	_, err := rand.Read(b)
	if err != nil {
		return apiHosts[time.Now().UnixNano()%int64(len(apiHosts))]
	}
	randInt := binary.BigEndian.Uint64(b)
	return apiHosts[randInt%uint64(len(apiHosts))]
}
